import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Choreo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.title}>
            <span>Choreo</span>
          </h1>
          <img className={styles.familyImg} src="/images/family.jpeg" alt="Vercel Logo" />


          <ul className={styles.features}>
            <li>Eliminar los conflictos por las tareas domesticas</li>
            <li>Visibilizar la carga física y mental</li>
            <li>Conseguir un reparto de tareas más justo y equilibrado</li>
          </ul>

        </div>

        <div className={styles.grid}>
          <label>Escribe el código de acceso a tu tablero</label>
          <div className={styles.codeform}>
            <input type="text"/>
            <button>Entrar</button>
          </div>
          <span className={styles.separator}>o</span>
          <button>Crear un tablero nuevo</button>
        </div>
      </main>
    </div>
  )
}
