micronaut:
  application:
    name: choreo
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: "classpath:static"
  server:
    cors:
      enabled: false

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/yourdb`}
    username: ${JDBC_USER:yourdbUser}
    password: ${JDBC_PASSWORD:`yourdbpwd`}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

flyway:
  datasources:
    default:
      baselineOnMigrate: true
      baselineVersion: 1
      enabled: ${ENABLE_FLYWAY:false}

jpa:
  default:
    show_sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
